language: rust

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

branches:
  except:
    # Used by bors
    - staging.tmp

rust:
    - nightly

os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.xargo
    - $TRAVIS_BUILD_DIR/target

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - (test -x $HOME/.cargo/bin/bootimage || cargo install bootimage)
  - cargo install-update -a

script:
  - bootimage build
