language: rust

rust:
    - nightly-2017-03-04

cache: cargo

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
  - source ~/.cargo/env
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/rustfmt || cargo install rustfmt)
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - RUST_BACKTRACE=1 cargo install-update -a

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

addons:
  apt:
    packages:
      - nasm

script:
  - make
  - cargo fmt -- --write-mode=diff
