language: rust

sudo: false

notifications:
    email:
        on_success: never
        on_failure: change

branches:
  except:
    # Used by bors
    - staging.tmp

rust:
    - nightly

os:
  - linux
  - osx
  - windows

cache:
  cargo: true
  directories:
    - $HOME/Library/Caches/Homebrew

addons:
  apt:
    packages:
      - qemu-system-x86

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; brew install qemu; fi
  - if [ $TRAVIS_OS_NAME = windows ]; then wget https://qemu.weilnetz.de/w64/2018/qemu-w64-setup-20180801.exe; 7z x qemu-w64-setup-20180801.exe; fi

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-update-installed || cargo install cargo-update-installed)
  - (test -x $HOME/.cargo/bin/cargo-xbuild || cargo install cargo-xbuild)
  - (test -x $HOME/.cargo/bin/bootimage || cargo install bootimage)
  - cargo update-installed

script:
  - bootimage build
  - cargo test
  - bootimage test
