# Documentation: https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'staging.tmp'

pool:
  vmImage: ubuntu-16.04

steps:
- bash: |
    echo "Hello world from $AGENT_NAME running on $AGENT_OS"
    echo "Reason: $BUILD_REASON"
    echo "Requested for: $BUILD_REQUESTEDFOR"
  displayName: 'Build Info'
  continueOnError: true

- bash: curl -sL https://github.com/getzola/zola/releases/download/v0.7.0/zola-v0.7.0-x86_64-unknown-linux-gnu.tar.gz | tar zxv
  displayName: "Download Zola"

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install Python Tools'

- script: python -m pip install --user -r requirements.txt
  displayName: 'Install Python Libraries'
  workingDirectory: "blog"

- script: python before_build.py
  displayName: "Run before_build.py script"
  workingDirectory: "blog"

- script: ../zola build
  displayName: "Build Site"
  workingDirectory: "blog"

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'generated_site'
    targetPath: 'blog/public'
